x-logging: &base-logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "5"
services:
  app:
    init: true
    build:
      context: ./dockerfiles/nodejs
    ports:
      - 3000:3000
    volumes:
      - output:/mnt
    working_dir: /mnt
    command: npm start
    logging: *base-logging
volumes:
  output: