x-logging: &base-logging
  driver: 'json-file'
  options:
    max-size: '10m'
    max-file: '5'
services:
  node:
    init: true
    build:
      context: ./dockerfiles/node
      target: app
    ports:
      - 3000:3000
      - 8000:8000
      - 9229:9229
    volumes:
      - .:/mnt
    working_dir: /mnt
    command: npm run dev
    logging: *base-logging
    depends_on:
      - postgres
      - redis
  postgres:
    init: true
    image: postgres:18
    command: ['-c', 'config_file=/etc/postgresql/postgresql.conf']
    volumes:
      - ./dockerfiles/postgres/postgresql.conf:/etc/postgresql/postgresql.conf
      - ./dockerfiles/postgres/initdb.d:/docker-entrypoint-initdb.d
      - pg-data:/var/lib/postgresql
    environment:
      POSTGRES_PASSWORD: ${COMPOSE_POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${COMPOSE_PG_DB_NAME:-postgres}
    ports:
      - ${COMPOSE_PUBLISH_PG_PORT:-5432}:5432
    logging: *base-logging
  redis:
    init: true
    build:
      context: ./dockerfiles/redis
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
    logging: *base-logging
volumes:
  pg-data:
  redis-data:
