x-logging: &base-logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "5"
services:
  workspace:
    init: true
    build:
      context: ./dockerfiles/nodejs
    volumes:
      - .:/mnt
    logging: *base-logging